/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdsManagerRouteImport } from './routes/ads-manager'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as BountiesRouteImport } from './routes/bounties'
import { Route as CirclesRouteImport } from './routes/circles'
import { Route as CreatorHubRouteImport } from './routes/creator-hub'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EscrowRouteImport } from './routes/escrow'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HelpBoardRouteImport } from './routes/help-board'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PurchaseAssistantRouteImport } from './routes/purchase-assistant'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as ReportProblemRouteImport } from './routes/report-problem'
import { Route as SellerHubRouteImport } from './routes/seller-hub'
import { Route as SellersRouteImport } from './routes/sellers'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as DotwellKnownAppleAppSiteAssociationRouteImport } from './routes/[.]well-known.apple-app-site-association'
import { Route as DotwellKnownAssetlinksDotjsonRouteImport } from './routes/[.]well-known.assetlinks[.]json'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAdInquiriesRouteImport } from './routes/admin.ad-inquiries'
import { Route as AdminAffiliatesRouteImport } from './routes/admin.affiliates'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminBountiesRouteImport } from './routes/admin.bounties'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminCashbackWalletRouteImport } from './routes/admin.cashback-wallet'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCircleCategoriesRouteImport } from './routes/admin.circle-categories'
import { Route as AdminCommunicationsRouteImport } from './routes/admin.communications'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminFeaturesRouteImport } from './routes/admin.features'
import { Route as AdminLedgerRouteImport } from './routes/admin.ledger'
import { Route as AdminManagementUsersRouteImport } from './routes/admin.management-users'
import { Route as AdminManualPaymentsRouteImport } from './routes/admin.manual-payments'
import { Route as AdminMarketplaceControlsRouteImport } from './routes/admin.marketplace-controls'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminProductTagsRouteImport } from './routes/admin.product-tags'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminReconciliationRouteImport } from './routes/admin.reconciliation'
import { Route as AdminReferralsRouteImport } from './routes/admin.referrals'
import { Route as AdminRefundsRouteImport } from './routes/admin.refunds'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminSellerVerificationRouteImport } from './routes/admin.seller-verification'
import { Route as AdminSellersRouteImport } from './routes/admin.sellers'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSystemWalletsRouteImport } from './routes/admin.system-wallets'
import { Route as AdminToolsRouteImport } from './routes/admin.tools'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminVisitorsRouteImport } from './routes/admin.visitors'
import { Route as AdsManagerIdRouteImport } from './routes/ads-manager.$id'
import { Route as ApiCreatorCoachRouteImport } from './routes/api/creator-coach'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as CreatorsHandleRouteImport } from './routes/creators_.$handle'
import { Route as CreatorsDiscoverRouteImport } from './routes/creators_.discover'
import { Route as CreatorsFollowingRouteImport } from './routes/creators_.following'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as PaymentReturnRouteImport } from './routes/payment.return'
import { Route as PostIdRouteImport } from './routes/post.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as ShopIdRouteImport } from './routes/shop.$id'
import { Route as WalletIndexRouteImport } from './routes/wallet.index'
import { Route as WalletHistoryRouteImport } from './routes/wallet.history'
import { Route as WalletLedgerRouteImport } from './routes/wallet.ledger'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'
import { Route as ApiPublicCryptoWebhookRouteImport } from './routes/api/public/crypto-webhook'
import { Route as ApiPublicFlutterwaveWebhookRouteImport } from './routes/api/public/flutterwave-webhook'
import { Route as ApiPublicPaymentReturnRouteImport } from './routes/api/public/payment-return'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as CreatorsCollectionsIdRouteImport } from './routes/creators_.collections.$id'
import { Route as ApiPublicHooksAutoReleaseOrdersRouteImport } from './routes/api/public/hooks/auto-release-orders'
import { Route as ApiPublicHooksPurgeDeletedAccountsRouteImport } from './routes/api/public/hooks/purge-deleted-accounts'
import { Route as ApiPublicHooksPushDispatchRouteImport } from './routes/api/public/hooks/push-dispatch'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img.$'
import { Route as ApiPublicPIdRouteImport } from './routes/api/public/p.$id'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ProfileIdItemKindItemIdRouteImport } from './routes/profile.$id.item.$kind.$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsManagerRoute = AdsManagerRouteImport.update({
  id: '/ads-manager',
  path: '/ads-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const BountiesRoute = BountiesRouteImport.update({
  id: '/bounties',
  path: '/bounties',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesRoute = CirclesRouteImport.update({
  id: '/circles',
  path: '/circles',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorHubRoute = CreatorHubRouteImport.update({
  id: '/creator-hub',
  path: '/creator-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EscrowRoute = EscrowRouteImport.update({
  id: '/escrow',
  path: '/escrow',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpBoardRoute = HelpBoardRouteImport.update({
  id: '/help-board',
  path: '/help-board',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseAssistantRoute = PurchaseAssistantRouteImport.update({
  id: '/purchase-assistant',
  path: '/purchase-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportProblemRoute = ReportProblemRouteImport.update({
  id: '/report-problem',
  path: '/report-problem',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerHubRoute = SellerHubRouteImport.update({
  id: '/seller-hub',
  path: '/seller-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersRoute = SellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAppleAppSiteAssociationRoute =
  DotwellKnownAppleAppSiteAssociationRouteImport.update({
    id: '/.well-known/apple-app-site-association',
    path: '/.well-known/apple-app-site-association',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAssetlinksDotjsonRoute =
  DotwellKnownAssetlinksDotjsonRouteImport.update({
    id: '/.well-known/assetlinks.json',
    path: '/.well-known/assetlinks.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdInquiriesRoute = AdminAdInquiriesRouteImport.update({
  id: '/ad-inquiries',
  path: '/ad-inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAffiliatesRoute = AdminAffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBountiesRoute = AdminBountiesRouteImport.update({
  id: '/bounties',
  path: '/bounties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCashbackWalletRoute = AdminCashbackWalletRouteImport.update({
  id: '/cashback-wallet',
  path: '/cashback-wallet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCircleCategoriesRoute = AdminCircleCategoriesRouteImport.update({
  id: '/circle-categories',
  path: '/circle-categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunicationsRoute = AdminCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeaturesRoute = AdminFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLedgerRoute = AdminLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManagementUsersRoute = AdminManagementUsersRouteImport.update({
  id: '/management-users',
  path: '/management-users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManualPaymentsRoute = AdminManualPaymentsRouteImport.update({
  id: '/manual-payments',
  path: '/manual-payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketplaceControlsRoute =
  AdminMarketplaceControlsRouteImport.update({
    id: '/marketplace-controls',
    path: '/marketplace-controls',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductTagsRoute = AdminProductTagsRouteImport.update({
  id: '/product-tags',
  path: '/product-tags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReconciliationRoute = AdminReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReferralsRoute = AdminReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRefundsRoute = AdminRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellerVerificationRoute = AdminSellerVerificationRouteImport.update({
  id: '/seller-verification',
  path: '/seller-verification',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellersRoute = AdminSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemWalletsRoute = AdminSystemWalletsRouteImport.update({
  id: '/system-wallets',
  path: '/system-wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToolsRoute = AdminToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVisitorsRoute = AdminVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AdminRoute,
} as any)
const AdsManagerIdRoute = AdsManagerIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdsManagerRoute,
} as any)
const ApiCreatorCoachRoute = ApiCreatorCoachRouteImport.update({
  id: '/api/creator-coach',
  path: '/api/creator-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsHandleRoute = CreatorsHandleRouteImport.update({
  id: '/creators_/$handle',
  path: '/creators/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsDiscoverRoute = CreatorsDiscoverRouteImport.update({
  id: '/creators_/discover',
  path: '/creators/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsFollowingRoute = CreatorsFollowingRouteImport.update({
  id: '/creators_/following',
  path: '/creators/following',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentReturnRoute = PaymentReturnRouteImport.update({
  id: '/payment/return',
  path: '/payment/return',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIdRoute = ShopIdRouteImport.update({
  id: '/shop/$id',
  path: '/shop/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WalletRoute,
} as any)
const WalletHistoryRoute = WalletHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => WalletRoute,
} as any)
const WalletLedgerRoute = WalletLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => WalletRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminBlogRoute,
} as any)
const ApiPublicCryptoWebhookRoute = ApiPublicCryptoWebhookRouteImport.update({
  id: '/api/public/crypto-webhook',
  path: '/api/public/crypto-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFlutterwaveWebhookRoute =
  ApiPublicFlutterwaveWebhookRouteImport.update({
    id: '/api/public/flutterwave-webhook',
    path: '/api/public/flutterwave-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentReturnRoute = ApiPublicPaymentReturnRouteImport.update({
  id: '/api/public/payment-return',
  path: '/api/public/payment-return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsCollectionsIdRoute = CreatorsCollectionsIdRouteImport.update({
  id: '/creators_/collections/$id',
  path: '/creators/collections/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAutoReleaseOrdersRoute =
  ApiPublicHooksAutoReleaseOrdersRouteImport.update({
    id: '/api/public/hooks/auto-release-orders',
    path: '/api/public/hooks/auto-release-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPurgeDeletedAccountsRoute =
  ApiPublicHooksPurgeDeletedAccountsRouteImport.update({
    id: '/api/public/hooks/purge-deleted-accounts',
    path: '/api/public/hooks/purge-deleted-accounts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPushDispatchRoute =
  ApiPublicHooksPushDispatchRouteImport.update({
    id: '/api/public/hooks/push-dispatch',
    path: '/api/public/hooks/push-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPIdRoute = ApiPublicPIdRouteImport.update({
  id: '/api/public/p/$id',
  path: '/api/public/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileIdItemKindItemIdRoute = ProfileIdItemKindItemIdRouteImport.update({
  id: '/item/$kind/$itemId',
  path: '/item/$kind/$itemId',
  getParentRoute: () => ProfileIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRouteWithChildren
  '/ads-manager': typeof AdsManagerRouteWithChildren
  '/advertise': typeof AdvertiseRoute
  '/affiliate': typeof AffiliateRoute
  '/bounties': typeof BountiesRoute
  '/circles': typeof CirclesRoute
  '/creator-hub': typeof CreatorHubRoute
  '/creators': typeof CreatorsRoute
  '/dashboard': typeof DashboardRoute
  '/escrow': typeof EscrowRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/feed': typeof FeedRoute
  '/help': typeof HelpRoute
  '/help-board': typeof HelpBoardRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/purchase-assistant': typeof PurchaseAssistantRoute
  '/referrals': typeof ReferralsRoute
  '/refunds': typeof RefundsRoute
  '/report-problem': typeof ReportProblemRoute
  '/seller-hub': typeof SellerHubRoute
  '/sellers': typeof SellersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/admin/ad-inquiries': typeof AdminAdInquiriesRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/bounties': typeof AdminBountiesRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/cashback-wallet': typeof AdminCashbackWalletRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/circle-categories': typeof AdminCircleCategoriesRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/management-users': typeof AdminManagementUsersRoute
  '/admin/manual-payments': typeof AdminManualPaymentsRoute
  '/admin/marketplace-controls': typeof AdminMarketplaceControlsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/product-tags': typeof AdminProductTagsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reconciliation': typeof AdminReconciliationRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seller-verification': typeof AdminSellerVerificationRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system-wallets': typeof AdminSystemWalletsRoute
  '/admin/tools': typeof AdminToolsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/ads-manager/$id': typeof AdsManagerIdRoute
  '/api/creator-coach': typeof ApiCreatorCoachRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/creators/$handle': typeof CreatorsHandleRoute
  '/creators/discover': typeof CreatorsDiscoverRoute
  '/creators/following': typeof CreatorsFollowingRoute
  '/order/$id': typeof OrderIdRoute
  '/payment/return': typeof PaymentReturnRoute
  '/post/$id': typeof PostIdRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/shop/$id': typeof ShopIdRoute
  '/wallet/history': typeof WalletHistoryRoute
  '/wallet/ledger': typeof WalletLedgerRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/api/public/crypto-webhook': typeof ApiPublicCryptoWebhookRoute
  '/api/public/flutterwave-webhook': typeof ApiPublicFlutterwaveWebhookRoute
  '/api/public/payment-return': typeof ApiPublicPaymentReturnRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/creators/collections/$id': typeof CreatorsCollectionsIdRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/api/public/hooks/auto-release-orders': typeof ApiPublicHooksAutoReleaseOrdersRoute
  '/api/public/hooks/purge-deleted-accounts': typeof ApiPublicHooksPurgeDeletedAccountsRoute
  '/api/public/hooks/push-dispatch': typeof ApiPublicHooksPushDispatchRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/p/$id': typeof ApiPublicPIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/profile/$id/item/$kind/$itemId': typeof ProfileIdItemKindItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/ads-manager': typeof AdsManagerRouteWithChildren
  '/advertise': typeof AdvertiseRoute
  '/affiliate': typeof AffiliateRoute
  '/bounties': typeof BountiesRoute
  '/circles': typeof CirclesRoute
  '/creator-hub': typeof CreatorHubRoute
  '/creators': typeof CreatorsRoute
  '/dashboard': typeof DashboardRoute
  '/escrow': typeof EscrowRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/feed': typeof FeedRoute
  '/help': typeof HelpRoute
  '/help-board': typeof HelpBoardRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/purchase-assistant': typeof PurchaseAssistantRoute
  '/referrals': typeof ReferralsRoute
  '/refunds': typeof RefundsRoute
  '/report-problem': typeof ReportProblemRoute
  '/seller-hub': typeof SellerHubRoute
  '/sellers': typeof SellersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/admin/ad-inquiries': typeof AdminAdInquiriesRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bounties': typeof AdminBountiesRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/cashback-wallet': typeof AdminCashbackWalletRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/circle-categories': typeof AdminCircleCategoriesRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/management-users': typeof AdminManagementUsersRoute
  '/admin/manual-payments': typeof AdminManualPaymentsRoute
  '/admin/marketplace-controls': typeof AdminMarketplaceControlsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/product-tags': typeof AdminProductTagsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reconciliation': typeof AdminReconciliationRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seller-verification': typeof AdminSellerVerificationRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system-wallets': typeof AdminSystemWalletsRoute
  '/admin/tools': typeof AdminToolsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/ads-manager/$id': typeof AdsManagerIdRoute
  '/api/creator-coach': typeof ApiCreatorCoachRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/creators/$handle': typeof CreatorsHandleRoute
  '/creators/discover': typeof CreatorsDiscoverRoute
  '/creators/following': typeof CreatorsFollowingRoute
  '/order/$id': typeof OrderIdRoute
  '/payment/return': typeof PaymentReturnRoute
  '/post/$id': typeof PostIdRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/shop/$id': typeof ShopIdRoute
  '/wallet/history': typeof WalletHistoryRoute
  '/wallet/ledger': typeof WalletLedgerRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/wallet': typeof WalletIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/api/public/crypto-webhook': typeof ApiPublicCryptoWebhookRoute
  '/api/public/flutterwave-webhook': typeof ApiPublicFlutterwaveWebhookRoute
  '/api/public/payment-return': typeof ApiPublicPaymentReturnRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/creators/collections/$id': typeof CreatorsCollectionsIdRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/api/public/hooks/auto-release-orders': typeof ApiPublicHooksAutoReleaseOrdersRoute
  '/api/public/hooks/purge-deleted-accounts': typeof ApiPublicHooksPurgeDeletedAccountsRoute
  '/api/public/hooks/push-dispatch': typeof ApiPublicHooksPushDispatchRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/p/$id': typeof ApiPublicPIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/profile/$id/item/$kind/$itemId': typeof ProfileIdItemKindItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRouteWithChildren
  '/ads-manager': typeof AdsManagerRouteWithChildren
  '/advertise': typeof AdvertiseRoute
  '/affiliate': typeof AffiliateRoute
  '/bounties': typeof BountiesRoute
  '/circles': typeof CirclesRoute
  '/creator-hub': typeof CreatorHubRoute
  '/creators': typeof CreatorsRoute
  '/dashboard': typeof DashboardRoute
  '/escrow': typeof EscrowRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/feed': typeof FeedRoute
  '/help': typeof HelpRoute
  '/help-board': typeof HelpBoardRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/purchase-assistant': typeof PurchaseAssistantRoute
  '/referrals': typeof ReferralsRoute
  '/refunds': typeof RefundsRoute
  '/report-problem': typeof ReportProblemRoute
  '/seller-hub': typeof SellerHubRoute
  '/sellers': typeof SellersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/admin/ad-inquiries': typeof AdminAdInquiriesRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/bounties': typeof AdminBountiesRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/cashback-wallet': typeof AdminCashbackWalletRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/circle-categories': typeof AdminCircleCategoriesRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/management-users': typeof AdminManagementUsersRoute
  '/admin/manual-payments': typeof AdminManualPaymentsRoute
  '/admin/marketplace-controls': typeof AdminMarketplaceControlsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/product-tags': typeof AdminProductTagsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reconciliation': typeof AdminReconciliationRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seller-verification': typeof AdminSellerVerificationRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system-wallets': typeof AdminSystemWalletsRoute
  '/admin/tools': typeof AdminToolsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/ads-manager/$id': typeof AdsManagerIdRoute
  '/api/creator-coach': typeof ApiCreatorCoachRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/creators_/$handle': typeof CreatorsHandleRoute
  '/creators_/discover': typeof CreatorsDiscoverRoute
  '/creators_/following': typeof CreatorsFollowingRoute
  '/order/$id': typeof OrderIdRoute
  '/payment/return': typeof PaymentReturnRoute
  '/post/$id': typeof PostIdRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/shop/$id': typeof ShopIdRoute
  '/wallet/history': typeof WalletHistoryRoute
  '/wallet/ledger': typeof WalletLedgerRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/api/public/crypto-webhook': typeof ApiPublicCryptoWebhookRoute
  '/api/public/flutterwave-webhook': typeof ApiPublicFlutterwaveWebhookRoute
  '/api/public/payment-return': typeof ApiPublicPaymentReturnRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/creators_/collections/$id': typeof CreatorsCollectionsIdRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/api/public/hooks/auto-release-orders': typeof ApiPublicHooksAutoReleaseOrdersRoute
  '/api/public/hooks/purge-deleted-accounts': typeof ApiPublicHooksPurgeDeletedAccountsRoute
  '/api/public/hooks/push-dispatch': typeof ApiPublicHooksPushDispatchRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/p/$id': typeof ApiPublicPIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/profile/$id/item/$kind/$itemId': typeof ProfileIdItemKindItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/admin'
    | '/ads-manager'
    | '/advertise'
    | '/affiliate'
    | '/bounties'
    | '/circles'
    | '/creator-hub'
    | '/creators'
    | '/dashboard'
    | '/escrow'
    | '/explore'
    | '/faq'
    | '/feed'
    | '/help'
    | '/help-board'
    | '/marketplace'
    | '/messages'
    | '/privacy'
    | '/purchase-assistant'
    | '/referrals'
    | '/refunds'
    | '/report-problem'
    | '/seller-hub'
    | '/sellers'
    | '/sitemap.xml'
    | '/terms'
    | '/wallet'
    | '/.well-known/apple-app-site-association'
    | '/.well-known/assetlinks.json'
    | '/admin/ad-inquiries'
    | '/admin/affiliates'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/bounties'
    | '/admin/campaigns'
    | '/admin/cashback-wallet'
    | '/admin/categories'
    | '/admin/circle-categories'
    | '/admin/communications'
    | '/admin/coupons'
    | '/admin/courses'
    | '/admin/disputes'
    | '/admin/features'
    | '/admin/ledger'
    | '/admin/management-users'
    | '/admin/manual-payments'
    | '/admin/marketplace-controls'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/product-tags'
    | '/admin/products'
    | '/admin/reconciliation'
    | '/admin/referrals'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/seller-verification'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/system-wallets'
    | '/admin/tools'
    | '/admin/users'
    | '/admin/visitors'
    | '/ads-manager/$id'
    | '/api/creator-coach'
    | '/blog/$slug'
    | '/checkout/$id'
    | '/creators/$handle'
    | '/creators/discover'
    | '/creators/following'
    | '/order/$id'
    | '/payment/return'
    | '/post/$id'
    | '/product/$id'
    | '/profile/$id'
    | '/shop/$id'
    | '/wallet/history'
    | '/wallet/ledger'
    | '/admin/'
    | '/blog/'
    | '/wallet/'
    | '/admin/blog/$id'
    | '/api/public/crypto-webhook'
    | '/api/public/flutterwave-webhook'
    | '/api/public/payment-return'
    | '/api/public/paystack-webhook'
    | '/api/public/track'
    | '/creators/collections/$id'
    | '/admin/blog/'
    | '/api/public/hooks/auto-release-orders'
    | '/api/public/hooks/purge-deleted-accounts'
    | '/api/public/hooks/push-dispatch'
    | '/api/public/img/$'
    | '/api/public/p/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/profile/$id/item/$kind/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academy'
    | '/ads-manager'
    | '/advertise'
    | '/affiliate'
    | '/bounties'
    | '/circles'
    | '/creator-hub'
    | '/creators'
    | '/dashboard'
    | '/escrow'
    | '/explore'
    | '/faq'
    | '/feed'
    | '/help'
    | '/help-board'
    | '/marketplace'
    | '/messages'
    | '/privacy'
    | '/purchase-assistant'
    | '/referrals'
    | '/refunds'
    | '/report-problem'
    | '/seller-hub'
    | '/sellers'
    | '/sitemap.xml'
    | '/terms'
    | '/.well-known/apple-app-site-association'
    | '/.well-known/assetlinks.json'
    | '/admin/ad-inquiries'
    | '/admin/affiliates'
    | '/admin/audit'
    | '/admin/bounties'
    | '/admin/campaigns'
    | '/admin/cashback-wallet'
    | '/admin/categories'
    | '/admin/circle-categories'
    | '/admin/communications'
    | '/admin/coupons'
    | '/admin/courses'
    | '/admin/disputes'
    | '/admin/features'
    | '/admin/ledger'
    | '/admin/management-users'
    | '/admin/manual-payments'
    | '/admin/marketplace-controls'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/product-tags'
    | '/admin/products'
    | '/admin/reconciliation'
    | '/admin/referrals'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/seller-verification'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/system-wallets'
    | '/admin/tools'
    | '/admin/users'
    | '/admin/visitors'
    | '/ads-manager/$id'
    | '/api/creator-coach'
    | '/blog/$slug'
    | '/checkout/$id'
    | '/creators/$handle'
    | '/creators/discover'
    | '/creators/following'
    | '/order/$id'
    | '/payment/return'
    | '/post/$id'
    | '/product/$id'
    | '/profile/$id'
    | '/shop/$id'
    | '/wallet/history'
    | '/wallet/ledger'
    | '/admin'
    | '/blog'
    | '/wallet'
    | '/admin/blog/$id'
    | '/api/public/crypto-webhook'
    | '/api/public/flutterwave-webhook'
    | '/api/public/payment-return'
    | '/api/public/paystack-webhook'
    | '/api/public/track'
    | '/creators/collections/$id'
    | '/admin/blog'
    | '/api/public/hooks/auto-release-orders'
    | '/api/public/hooks/purge-deleted-accounts'
    | '/api/public/hooks/push-dispatch'
    | '/api/public/img/$'
    | '/api/public/p/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/profile/$id/item/$kind/$itemId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academy'
    | '/admin'
    | '/ads-manager'
    | '/advertise'
    | '/affiliate'
    | '/bounties'
    | '/circles'
    | '/creator-hub'
    | '/creators'
    | '/dashboard'
    | '/escrow'
    | '/explore'
    | '/faq'
    | '/feed'
    | '/help'
    | '/help-board'
    | '/marketplace'
    | '/messages'
    | '/privacy'
    | '/purchase-assistant'
    | '/referrals'
    | '/refunds'
    | '/report-problem'
    | '/seller-hub'
    | '/sellers'
    | '/sitemap.xml'
    | '/terms'
    | '/wallet'
    | '/.well-known/apple-app-site-association'
    | '/.well-known/assetlinks.json'
    | '/admin/ad-inquiries'
    | '/admin/affiliates'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/bounties'
    | '/admin/campaigns'
    | '/admin/cashback-wallet'
    | '/admin/categories'
    | '/admin/circle-categories'
    | '/admin/communications'
    | '/admin/coupons'
    | '/admin/courses'
    | '/admin/disputes'
    | '/admin/features'
    | '/admin/ledger'
    | '/admin/management-users'
    | '/admin/manual-payments'
    | '/admin/marketplace-controls'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/product-tags'
    | '/admin/products'
    | '/admin/reconciliation'
    | '/admin/referrals'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/seller-verification'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/system-wallets'
    | '/admin/tools'
    | '/admin/users'
    | '/admin/visitors'
    | '/ads-manager/$id'
    | '/api/creator-coach'
    | '/blog/$slug'
    | '/checkout/$id'
    | '/creators_/$handle'
    | '/creators_/discover'
    | '/creators_/following'
    | '/order/$id'
    | '/payment/return'
    | '/post/$id'
    | '/product/$id'
    | '/profile/$id'
    | '/shop/$id'
    | '/wallet/history'
    | '/wallet/ledger'
    | '/admin/'
    | '/blog/'
    | '/wallet/'
    | '/admin/blog/$id'
    | '/api/public/crypto-webhook'
    | '/api/public/flutterwave-webhook'
    | '/api/public/payment-return'
    | '/api/public/paystack-webhook'
    | '/api/public/track'
    | '/creators_/collections/$id'
    | '/admin/blog/'
    | '/api/public/hooks/auto-release-orders'
    | '/api/public/hooks/purge-deleted-accounts'
    | '/api/public/hooks/push-dispatch'
    | '/api/public/img/$'
    | '/api/public/p/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/profile/$id/item/$kind/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdsManagerRoute: typeof AdsManagerRouteWithChildren
  AdvertiseRoute: typeof AdvertiseRoute
  AffiliateRoute: typeof AffiliateRoute
  BountiesRoute: typeof BountiesRoute
  CirclesRoute: typeof CirclesRoute
  CreatorHubRoute: typeof CreatorHubRoute
  CreatorsRoute: typeof CreatorsRoute
  DashboardRoute: typeof DashboardRoute
  EscrowRoute: typeof EscrowRoute
  ExploreRoute: typeof ExploreRoute
  FaqRoute: typeof FaqRoute
  FeedRoute: typeof FeedRoute
  HelpRoute: typeof HelpRoute
  HelpBoardRoute: typeof HelpBoardRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MessagesRoute: typeof MessagesRoute
  PrivacyRoute: typeof PrivacyRoute
  PurchaseAssistantRoute: typeof PurchaseAssistantRoute
  ReferralsRoute: typeof ReferralsRoute
  RefundsRoute: typeof RefundsRoute
  ReportProblemRoute: typeof ReportProblemRoute
  SellerHubRoute: typeof SellerHubRoute
  SellersRoute: typeof SellersRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WalletRoute: typeof WalletRouteWithChildren
  DotwellKnownAppleAppSiteAssociationRoute: typeof DotwellKnownAppleAppSiteAssociationRoute
  DotwellKnownAssetlinksDotjsonRoute: typeof DotwellKnownAssetlinksDotjsonRoute
  ApiCreatorCoachRoute: typeof ApiCreatorCoachRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  CreatorsHandleRoute: typeof CreatorsHandleRoute
  CreatorsDiscoverRoute: typeof CreatorsDiscoverRoute
  CreatorsFollowingRoute: typeof CreatorsFollowingRoute
  OrderIdRoute: typeof OrderIdRoute
  PaymentReturnRoute: typeof PaymentReturnRoute
  PostIdRoute: typeof PostIdRoute
  ProductIdRoute: typeof ProductIdRoute
  ProfileIdRoute: typeof ProfileIdRouteWithChildren
  ShopIdRoute: typeof ShopIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicCryptoWebhookRoute: typeof ApiPublicCryptoWebhookRoute
  ApiPublicFlutterwaveWebhookRoute: typeof ApiPublicFlutterwaveWebhookRoute
  ApiPublicPaymentReturnRoute: typeof ApiPublicPaymentReturnRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  CreatorsCollectionsIdRoute: typeof CreatorsCollectionsIdRoute
  ApiPublicHooksAutoReleaseOrdersRoute: typeof ApiPublicHooksAutoReleaseOrdersRoute
  ApiPublicHooksPurgeDeletedAccountsRoute: typeof ApiPublicHooksPurgeDeletedAccountsRoute
  ApiPublicHooksPushDispatchRoute: typeof ApiPublicHooksPushDispatchRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
  ApiPublicPIdRoute: typeof ApiPublicPIdRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads-manager': {
      id: '/ads-manager'
      path: '/ads-manager'
      fullPath: '/ads-manager'
      preLoaderRoute: typeof AdsManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bounties': {
      id: '/bounties'
      path: '/bounties'
      fullPath: '/bounties'
      preLoaderRoute: typeof BountiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles': {
      id: '/circles'
      path: '/circles'
      fullPath: '/circles'
      preLoaderRoute: typeof CirclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-hub': {
      id: '/creator-hub'
      path: '/creator-hub'
      fullPath: '/creator-hub'
      preLoaderRoute: typeof CreatorHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escrow': {
      id: '/escrow'
      path: '/escrow'
      fullPath: '/escrow'
      preLoaderRoute: typeof EscrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-board': {
      id: '/help-board'
      path: '/help-board'
      fullPath: '/help-board'
      preLoaderRoute: typeof HelpBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-assistant': {
      id: '/purchase-assistant'
      path: '/purchase-assistant'
      fullPath: '/purchase-assistant'
      preLoaderRoute: typeof PurchaseAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-problem': {
      id: '/report-problem'
      path: '/report-problem'
      fullPath: '/report-problem'
      preLoaderRoute: typeof ReportProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-hub': {
      id: '/seller-hub'
      path: '/seller-hub'
      fullPath: '/seller-hub'
      preLoaderRoute: typeof SellerHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers': {
      id: '/sellers'
      path: '/sellers'
      fullPath: '/sellers'
      preLoaderRoute: typeof SellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/apple-app-site-association': {
      id: '/.well-known/apple-app-site-association'
      path: '/.well-known/apple-app-site-association'
      fullPath: '/.well-known/apple-app-site-association'
      preLoaderRoute: typeof DotwellKnownAppleAppSiteAssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/assetlinks.json': {
      id: '/.well-known/assetlinks.json'
      path: '/.well-known/assetlinks.json'
      fullPath: '/.well-known/assetlinks.json'
      preLoaderRoute: typeof DotwellKnownAssetlinksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ad-inquiries': {
      id: '/admin/ad-inquiries'
      path: '/ad-inquiries'
      fullPath: '/admin/ad-inquiries'
      preLoaderRoute: typeof AdminAdInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/affiliates': {
      id: '/admin/affiliates'
      path: '/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AdminAffiliatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bounties': {
      id: '/admin/bounties'
      path: '/bounties'
      fullPath: '/admin/bounties'
      preLoaderRoute: typeof AdminBountiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cashback-wallet': {
      id: '/admin/cashback-wallet'
      path: '/cashback-wallet'
      fullPath: '/admin/cashback-wallet'
      preLoaderRoute: typeof AdminCashbackWalletRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/circle-categories': {
      id: '/admin/circle-categories'
      path: '/circle-categories'
      fullPath: '/admin/circle-categories'
      preLoaderRoute: typeof AdminCircleCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communications': {
      id: '/admin/communications'
      path: '/communications'
      fullPath: '/admin/communications'
      preLoaderRoute: typeof AdminCommunicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/features': {
      id: '/admin/features'
      path: '/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AdminFeaturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ledger': {
      id: '/admin/ledger'
      path: '/ledger'
      fullPath: '/admin/ledger'
      preLoaderRoute: typeof AdminLedgerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/management-users': {
      id: '/admin/management-users'
      path: '/management-users'
      fullPath: '/admin/management-users'
      preLoaderRoute: typeof AdminManagementUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manual-payments': {
      id: '/admin/manual-payments'
      path: '/manual-payments'
      fullPath: '/admin/manual-payments'
      preLoaderRoute: typeof AdminManualPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketplace-controls': {
      id: '/admin/marketplace-controls'
      path: '/marketplace-controls'
      fullPath: '/admin/marketplace-controls'
      preLoaderRoute: typeof AdminMarketplaceControlsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/product-tags': {
      id: '/admin/product-tags'
      path: '/product-tags'
      fullPath: '/admin/product-tags'
      preLoaderRoute: typeof AdminProductTagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reconciliation': {
      id: '/admin/reconciliation'
      path: '/reconciliation'
      fullPath: '/admin/reconciliation'
      preLoaderRoute: typeof AdminReconciliationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/referrals': {
      id: '/admin/referrals'
      path: '/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AdminReferralsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/refunds': {
      id: '/admin/refunds'
      path: '/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AdminRefundsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seller-verification': {
      id: '/admin/seller-verification'
      path: '/seller-verification'
      fullPath: '/admin/seller-verification'
      preLoaderRoute: typeof AdminSellerVerificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sellers': {
      id: '/admin/sellers'
      path: '/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AdminSellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system-wallets': {
      id: '/admin/system-wallets'
      path: '/system-wallets'
      fullPath: '/admin/system-wallets'
      preLoaderRoute: typeof AdminSystemWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tools': {
      id: '/admin/tools'
      path: '/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AdminToolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/visitors': {
      id: '/admin/visitors'
      path: '/visitors'
      fullPath: '/admin/visitors'
      preLoaderRoute: typeof AdminVisitorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ads-manager/$id': {
      id: '/ads-manager/$id'
      path: '/$id'
      fullPath: '/ads-manager/$id'
      preLoaderRoute: typeof AdsManagerIdRouteImport
      parentRoute: typeof AdsManagerRoute
    }
    '/api/creator-coach': {
      id: '/api/creator-coach'
      path: '/api/creator-coach'
      fullPath: '/api/creator-coach'
      preLoaderRoute: typeof ApiCreatorCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators_/$handle': {
      id: '/creators_/$handle'
      path: '/creators/$handle'
      fullPath: '/creators/$handle'
      preLoaderRoute: typeof CreatorsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators_/discover': {
      id: '/creators_/discover'
      path: '/creators/discover'
      fullPath: '/creators/discover'
      preLoaderRoute: typeof CreatorsDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators_/following': {
      id: '/creators_/following'
      path: '/creators/following'
      fullPath: '/creators/following'
      preLoaderRoute: typeof CreatorsFollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/return': {
      id: '/payment/return'
      path: '/payment/return'
      fullPath: '/payment/return'
      preLoaderRoute: typeof PaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$id': {
      id: '/shop/$id'
      path: '/shop/$id'
      fullPath: '/shop/$id'
      preLoaderRoute: typeof ShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/'
      fullPath: '/wallet/'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/history': {
      id: '/wallet/history'
      path: '/history'
      fullPath: '/wallet/history'
      preLoaderRoute: typeof WalletHistoryRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/ledger': {
      id: '/wallet/ledger'
      path: '/ledger'
      fullPath: '/wallet/ledger'
      preLoaderRoute: typeof WalletLedgerRouteImport
      parentRoute: typeof WalletRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/api/public/crypto-webhook': {
      id: '/api/public/crypto-webhook'
      path: '/api/public/crypto-webhook'
      fullPath: '/api/public/crypto-webhook'
      preLoaderRoute: typeof ApiPublicCryptoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/flutterwave-webhook': {
      id: '/api/public/flutterwave-webhook'
      path: '/api/public/flutterwave-webhook'
      fullPath: '/api/public/flutterwave-webhook'
      preLoaderRoute: typeof ApiPublicFlutterwaveWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payment-return': {
      id: '/api/public/payment-return'
      path: '/api/public/payment-return'
      fullPath: '/api/public/payment-return'
      preLoaderRoute: typeof ApiPublicPaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators_/collections/$id': {
      id: '/creators_/collections/$id'
      path: '/creators/collections/$id'
      fullPath: '/creators/collections/$id'
      preLoaderRoute: typeof CreatorsCollectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-release-orders': {
      id: '/api/public/hooks/auto-release-orders'
      path: '/api/public/hooks/auto-release-orders'
      fullPath: '/api/public/hooks/auto-release-orders'
      preLoaderRoute: typeof ApiPublicHooksAutoReleaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/purge-deleted-accounts': {
      id: '/api/public/hooks/purge-deleted-accounts'
      path: '/api/public/hooks/purge-deleted-accounts'
      fullPath: '/api/public/hooks/purge-deleted-accounts'
      preLoaderRoute: typeof ApiPublicHooksPurgeDeletedAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/push-dispatch': {
      id: '/api/public/hooks/push-dispatch'
      path: '/api/public/hooks/push-dispatch'
      fullPath: '/api/public/hooks/push-dispatch'
      preLoaderRoute: typeof ApiPublicHooksPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/p/$id': {
      id: '/api/public/p/$id'
      path: '/api/public/p/$id'
      fullPath: '/api/public/p/$id'
      preLoaderRoute: typeof ApiPublicPIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id/item/$kind/$itemId': {
      id: '/profile/$id/item/$kind/$itemId'
      path: '/item/$kind/$itemId'
      fullPath: '/profile/$id/item/$kind/$itemId'
      preLoaderRoute: typeof ProfileIdItemKindItemIdRouteImport
      parentRoute: typeof ProfileIdRoute
    }
  }
}

interface AdminBlogRouteChildren {
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
}

const AdminBlogRouteChildren: AdminBlogRouteChildren = {
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
}

const AdminBlogRouteWithChildren = AdminBlogRoute._addFileChildren(
  AdminBlogRouteChildren,
)

interface AdminRouteChildren {
  AdminAdInquiriesRoute: typeof AdminAdInquiriesRoute
  AdminAffiliatesRoute: typeof AdminAffiliatesRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBlogRoute: typeof AdminBlogRouteWithChildren
  AdminBountiesRoute: typeof AdminBountiesRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminCashbackWalletRoute: typeof AdminCashbackWalletRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCircleCategoriesRoute: typeof AdminCircleCategoriesRoute
  AdminCommunicationsRoute: typeof AdminCommunicationsRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminFeaturesRoute: typeof AdminFeaturesRoute
  AdminLedgerRoute: typeof AdminLedgerRoute
  AdminManagementUsersRoute: typeof AdminManagementUsersRoute
  AdminManualPaymentsRoute: typeof AdminManualPaymentsRoute
  AdminMarketplaceControlsRoute: typeof AdminMarketplaceControlsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminProductTagsRoute: typeof AdminProductTagsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReconciliationRoute: typeof AdminReconciliationRoute
  AdminReferralsRoute: typeof AdminReferralsRoute
  AdminRefundsRoute: typeof AdminRefundsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSellerVerificationRoute: typeof AdminSellerVerificationRoute
  AdminSellersRoute: typeof AdminSellersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminSystemWalletsRoute: typeof AdminSystemWalletsRoute
  AdminToolsRoute: typeof AdminToolsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVisitorsRoute: typeof AdminVisitorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdInquiriesRoute: AdminAdInquiriesRoute,
  AdminAffiliatesRoute: AdminAffiliatesRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBlogRoute: AdminBlogRouteWithChildren,
  AdminBountiesRoute: AdminBountiesRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminCashbackWalletRoute: AdminCashbackWalletRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCircleCategoriesRoute: AdminCircleCategoriesRoute,
  AdminCommunicationsRoute: AdminCommunicationsRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminFeaturesRoute: AdminFeaturesRoute,
  AdminLedgerRoute: AdminLedgerRoute,
  AdminManagementUsersRoute: AdminManagementUsersRoute,
  AdminManualPaymentsRoute: AdminManualPaymentsRoute,
  AdminMarketplaceControlsRoute: AdminMarketplaceControlsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminProductTagsRoute: AdminProductTagsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReconciliationRoute: AdminReconciliationRoute,
  AdminReferralsRoute: AdminReferralsRoute,
  AdminRefundsRoute: AdminRefundsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSellerVerificationRoute: AdminSellerVerificationRoute,
  AdminSellersRoute: AdminSellersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminSystemWalletsRoute: AdminSystemWalletsRoute,
  AdminToolsRoute: AdminToolsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVisitorsRoute: AdminVisitorsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AdsManagerRouteChildren {
  AdsManagerIdRoute: typeof AdsManagerIdRoute
}

const AdsManagerRouteChildren: AdsManagerRouteChildren = {
  AdsManagerIdRoute: AdsManagerIdRoute,
}

const AdsManagerRouteWithChildren = AdsManagerRoute._addFileChildren(
  AdsManagerRouteChildren,
)

interface WalletRouteChildren {
  WalletHistoryRoute: typeof WalletHistoryRoute
  WalletLedgerRoute: typeof WalletLedgerRoute
  WalletIndexRoute: typeof WalletIndexRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletHistoryRoute: WalletHistoryRoute,
  WalletLedgerRoute: WalletLedgerRoute,
  WalletIndexRoute: WalletIndexRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

interface ProfileIdRouteChildren {
  ProfileIdItemKindItemIdRoute: typeof ProfileIdItemKindItemIdRoute
}

const ProfileIdRouteChildren: ProfileIdRouteChildren = {
  ProfileIdItemKindItemIdRoute: ProfileIdItemKindItemIdRoute,
}

const ProfileIdRouteWithChildren = ProfileIdRoute._addFileChildren(
  ProfileIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRoute,
  AdminRoute: AdminRouteWithChildren,
  AdsManagerRoute: AdsManagerRouteWithChildren,
  AdvertiseRoute: AdvertiseRoute,
  AffiliateRoute: AffiliateRoute,
  BountiesRoute: BountiesRoute,
  CirclesRoute: CirclesRoute,
  CreatorHubRoute: CreatorHubRoute,
  CreatorsRoute: CreatorsRoute,
  DashboardRoute: DashboardRoute,
  EscrowRoute: EscrowRoute,
  ExploreRoute: ExploreRoute,
  FaqRoute: FaqRoute,
  FeedRoute: FeedRoute,
  HelpRoute: HelpRoute,
  HelpBoardRoute: HelpBoardRoute,
  MarketplaceRoute: MarketplaceRoute,
  MessagesRoute: MessagesRoute,
  PrivacyRoute: PrivacyRoute,
  PurchaseAssistantRoute: PurchaseAssistantRoute,
  ReferralsRoute: ReferralsRoute,
  RefundsRoute: RefundsRoute,
  ReportProblemRoute: ReportProblemRoute,
  SellerHubRoute: SellerHubRoute,
  SellersRoute: SellersRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WalletRoute: WalletRouteWithChildren,
  DotwellKnownAppleAppSiteAssociationRoute:
    DotwellKnownAppleAppSiteAssociationRoute,
  DotwellKnownAssetlinksDotjsonRoute: DotwellKnownAssetlinksDotjsonRoute,
  ApiCreatorCoachRoute: ApiCreatorCoachRoute,
  BlogSlugRoute: BlogSlugRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  CreatorsHandleRoute: CreatorsHandleRoute,
  CreatorsDiscoverRoute: CreatorsDiscoverRoute,
  CreatorsFollowingRoute: CreatorsFollowingRoute,
  OrderIdRoute: OrderIdRoute,
  PaymentReturnRoute: PaymentReturnRoute,
  PostIdRoute: PostIdRoute,
  ProductIdRoute: ProductIdRoute,
  ProfileIdRoute: ProfileIdRouteWithChildren,
  ShopIdRoute: ShopIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicCryptoWebhookRoute: ApiPublicCryptoWebhookRoute,
  ApiPublicFlutterwaveWebhookRoute: ApiPublicFlutterwaveWebhookRoute,
  ApiPublicPaymentReturnRoute: ApiPublicPaymentReturnRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  CreatorsCollectionsIdRoute: CreatorsCollectionsIdRoute,
  ApiPublicHooksAutoReleaseOrdersRoute: ApiPublicHooksAutoReleaseOrdersRoute,
  ApiPublicHooksPurgeDeletedAccountsRoute:
    ApiPublicHooksPurgeDeletedAccountsRoute,
  ApiPublicHooksPushDispatchRoute: ApiPublicHooksPushDispatchRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
  ApiPublicPIdRoute: ApiPublicPIdRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
